language: python
python:
    - "2.7"

sudo: false
cache:
    pip: true
    directories:
        - "~/.platformio"
        - ".piolibdeps"

install:
    - pip install -U -e git+https://github.com/platformio/platformio@develop#egg=platformio

script:
    - platformio run
