language: python
python:
    - "2.7"

sudo: false
cache:
    pip: true
    directories:
        - "~/.platformio"
        - ".piolibdeps"

install:
    - pip install -r requirements.txt

script:
    - platformio run
